### ISSUE TITLE
关于图书馆搜索问题想请教一下，希冀您能回复一下

### ISSUE THREAD

**Issue by ExcaliburEX** [dommyet/JavlibraryBot#1]
图书馆的番剧详情页的网址后缀是` '?v=javli' `加上一个5位的随机序列包含数字和字母，我想问的是如何模拟爬虫搜索获取页面信息，毕竟普通的通过加番号后缀是无法获取对应番号的页面信息的。感谢回复:simple_smile:

**Comment by dommyet** [comment]
时间太久远了很多细节记不清了，而且之后从未维护过，我也不知道它现在还能不能正常跑。有印象的是你并不可以暴力猜测后缀的5位随机序列，似乎是服务器那边维护了一个用户的访问历史，只当用户是从搜索结果或首页或推荐页获得了这些序列，再点击进入某部电影时才可以正常访问。这份代码如果没记错的话应该在设计上就只能通过这种方法获得序列（`video_shortlink`  / `vlink`）所以当时跑起来是不会出现无法获取的情况的。

**Comment by ExcaliburEX** [comment]
感谢回复。也就是说每个人访问同一个影片获得网址后缀是不同的？

**Comment by dommyet** [comment]
每个电影的`video_shortlink`应该是唯一的。信息下载后我没有对它进行处理直接原样入库了，目的就是希望和服务器那边保持一致。偶尔会有信息订正或者演员改名的情况如果不一致的话又会导致头疼的问题。

**Comment by ExcaliburEX** [comment]
好的，谢谢，我再参考一下你的代码。
